---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myportfo/public_html/
    - cd /home/myportfo/repositories/employee-management-system
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
